### ISSUE TITLE
Plz tell me the procedure to integrate JT3DScrollview + Pods into and new xcode workspace. 

### ISSUE THREAD

**Issue by gauravdashora** [jonathantribouharet/JT3DScrollView#4]

**Comment by johnvuko** [comment]
Start by searching on google and next ask on stackoverflow.

https://guides.cocoapods.org/using/getting-started.html#toc_3
https://guides.cocoapods.org/using/using-cocoapods.html

**Comment by gauravdashora** [comment]
After fallowing this step i am still getting error 'JT3DScrollView' File not found. Lexial or preprocessor issue.

**Comment by gauravdashora** [comment]
when i added in viewcontroller.h

**Comment by johnvuko** [comment]
Check the example project, but don't use the same Podfile.

**Comment by gauravdashora** [comment]
No success same error. 'JT3DScrollView.h' File not found. Lexial or preprocessor when added in viewcontroller.h

**Comment by johnvuko** [comment]
Do you have installed cocoapod and do the `pod install` command?

**Comment by gauravdashora** [comment]
Yes both I have done it . I solved it by adding pods.debug and pods.release
in my project configuration files. Thank for your support.

On Tuesday, 21 July 2015, Jonathan Tribouharet notifications@github.com
wrote:

> Do you have installed cocoapod and do the pod install command?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jonathantribouharet/JT3DScrollView/issues/4#issuecomment-123278811
> .

## 

Gaurav Dashora
Director
Yashi Technoviz Private limited
Website: https://www.yashitechnoviz.com
